version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: customers
      - name: geolocation
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: sellers
      - name: product_category_translation