name: '_dbt'
version: '1.0.0'

profile: '_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  _dbt:
    +materialized: view
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table

on-run-start:
- "{% do run_query('create schema if not exists raw') %}"
- "{% do run_query('create schema if not exists staging') %}"
- "{% do run_query('create schema if not exists marts') %}"